# Generated by Django 5.2 on 2025-05-03 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('prioridad', models.CharField(choices=[(1, 'Critica'), (2, 'Alta'), (3, 'Media'), (4, 'Baja')], default=4)),
                ('estado', models.CharField(choices=[(1, 'Abierto'), (2, 'Cerrado'), (3, 'Resuelto'), (4, 'Reabierto')], default=1)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('calificacion', models.CharField(choices=[(1, 'Muy Buena'), (2, 'Buena'), (3, 'Normal'), (4, 'Baja'), (5, 'Muy Baja')], default=3)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('categoria', models.CharField(choices=[(1, 'Hardware'), (2, 'Software'), (3, 'Redes')], max_length=100)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('sla', models.IntegerField(max_length=2)),
            ],
            options={
                'verbose_name': 'Tipo de Ticket',
                'verbose_name_plural': 'Tipos de Tickets',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('mensaje', models.TextField(max_length=1000)),
                ('es_agente', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interacciones', to='helpdesk.ticket')),
            ],
            options={
                'verbose_name': 'Interacción de Ticket',
                'verbose_name_plural': 'Interacciones de Tickets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets_solicitados', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asignaciones', to='helpdesk.ticket')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historial', to='helpdesk.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cambios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Ticket',
                'verbose_name_plural': 'Historial de Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='helpdesk.tickettype'),
        ),
    ]
