# Generated by Django 5.2 on 2025-05-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Hardware'), (2, 'Software'), (3, 'Redes')], max_length=100),
        ),
    ]
