# Generated by Django 5.2 on 2025-05-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_tickettype_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='calificacion',
            field=models.IntegerField(choices=[(1, 'Muy Buena'), (2, 'Buena'), (3, 'Normal'), (4, 'Baja'), (5, 'Muy Baja')], default=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Abierto'), (2, 'Cerrado'), (3, 'Resuelto'), (4, 'Reabierto')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Critica'), (2, 'Alta'), (3, 'Media'), (4, 'Baja')], default=4),
        ),
    ]
