# Generated by Django 5.2 on 2025-05-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_ticket_solicitante_tickettype_grupo_soporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='solicitante',
        ),
    ]
