# Generated by Django 5.1.5 on 2025-01-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_categoria_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='c_campania',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supervisor',
        ),
    ]
